---
dependencies:
- name: "infrastructure"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.5"
- name: "application"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.51"
- name: "activiti-cloud-modeling"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.0.9"
